import { Anbieter, VertragKategorie } from '@/types/vertraege';

export const ANBIETER: Anbieter[] = [
  // STROM (4)
  {
    id: 'eon-strom',
    kategorie: 'strom',
    name: 'E.ON',
    preisProMonat: '8,90',
    laufzeit: '12 Monate',
    rating: 4,
    highlights: ['100% Ökostrom ♻', 'Bonus: €50 Gutschein', 'Keine Mindestlaufzeit'],
    empfohlen: true,
  },
  {
    id: 'vattenfall-strom',
    kategorie: 'strom',
    name: 'Vattenfall',
    preisProMonat: '7,40',
    laufzeit: '24 Monate',
    rating: 4,
    highlights: ['Günstigster Preis', 'Online-Abschluss'],
  },
  {
    id: 'enbw-strom',
    kategorie: 'strom',
    name: 'EnBW',
    preisProMonat: '9,20',
    laufzeit: '12 Monate',
    rating: 4,
    highlights: ['100% Ökostrom ♻', 'App-Steuerung'],
    partnerangebot: true,
  },
  {
    id: 'yello-strom',
    kategorie: 'strom',
    name: 'Yello Strom',
    preisProMonat: '8,10',
    laufzeit: '12 Monate',
    rating: 3,
    highlights: ['Keine Mindestlaufzeit', 'Bonus: €25'],
  },

  // INTERNET (4)
  {
    id: 'vodafone-internet',
    kategorie: 'internet',
    name: 'Vodafone',
    preisProMonat: '19,99',
    laufzeit: '24 Monate',
    rating: 4,
    highlights: ['250 Mbit/s', 'Keine Installationskosten'],
    empfohlen: true,
  },
  {
    id: 'telekom-internet',
    kategorie: 'internet',
    name: 'Telekom',
    preisProMonat: '24,99',
    laufzeit: '24 Monate',
    rating: 4,
    highlights: ['100 Mbit/s', 'Telekom EntertainTV'],
  },
  {
    id: 'o2-internet',
    kategorie: 'internet',
    name: 'o2',
    preisProMonat: '17,99',
    laufzeit: '12 Monate',
    rating: 4,
    highlights: ['50 Mbit/s', 'Keine Mindestlaufzeit'],
    partnerangebot: true,
  },
  {
    id: '1und1-internet',
    kategorie: 'internet',
    name: '1&1',
    preisProMonat: '16,99',
    laufzeit: '24 Monate',
    rating: 3,
    highlights: ['50 Mbit/s', 'Router inklusive'],
  },

  // TELEFON (4)
  {
    id: 'o2-telefon',
    kategorie: 'telefon',
    name: 'o2',
    preisProMonat: '9,99',
    laufzeit: '24 Monate',
    rating: 4,
    highlights: ['15 GB Daten', 'Allnet-Flat'],
    empfohlen: true,
  },
  {
    id: 'telekom-telefon',
    kategorie: 'telefon',
    name: 'Telekom',
    preisProMonat: '14,99',
    laufzeit: '24 Monate',
    rating: 4,
    highlights: ['20 GB Daten', 'VoLTE'],
  },
  {
    id: 'vodafone-telefon',
    kategorie: 'telefon',
    name: 'Vodafone',
    preisProMonat: '12,99',
    laufzeit: '24 Monate',
    rating: 4,
    highlights: ['20 GB Daten', 'EU-Roaming'],
    partnerangebot: true,
  },
  {
    id: 'alditalk-telefon',
    kategorie: 'telefon',
    name: 'Aldi Talk',
    preisProMonat: '7,99',
    laufzeit: 'Keine Laufzeit',
    rating: 3,
    highlights: ['8 GB Daten', 'Flexibel kündbar'],
  },

  // HAFTPFLICHT (4)
  {
    id: 'ergo-haftpflicht',
    kategorie: 'haftpflicht',
    name: 'ERGO',
    preisProMonat: '3,49',
    laufzeit: '12 Monate',
    rating: 4,
    highlights: ['Schutz ab 1€/Tag', 'Keine Selbstbeteiligung'],
    empfohlen: true,
  },
  {
    id: 'huk-haftpflicht',
    kategorie: 'haftpflicht',
    name: 'HUK-COBURG',
    preisProMonat: '2,90',
    laufzeit: '12 Monate',
    rating: 4,
    highlights: ['TÜV-geprüft', 'Sofortschutz'],
  },
  {
    id: 'allianz-haftpflicht',
    kategorie: 'haftpflicht',
    name: 'Allianz',
    preisProMonat: '4,20',
    laufzeit: '24 Monate',
    rating: 4,
    highlights: ['Premium-Schutz', 'Forderungsausfallschutz'],
    partnerangebot: true,
  },
  {
    id: 'axa-haftpflicht',
    kategorie: 'haftpflicht',
    name: 'AXA',
    preisProMonat: '3,10',
    laufzeit: '12 Monate',
    rating: 3,
    highlights: ['Keine Selbstbeteiligung', 'Online-Abschluss'],
  },

  // HAUSRAT (4)
  {
    id: 'huk-hausrat',
    kategorie: 'hausrat',
    name: 'HUK-COBURG',
    preisProMonat: '4,90',
    laufzeit: '12 Monate',
    rating: 4,
    highlights: ['Einbruchsschutz', 'Leitungswasser inklusive'],
    empfohlen: true,
  },
  {
    id: 'ergo-hausrat',
    kategorie: 'hausrat',
    name: 'ERGO',
    preisProMonat: '5,20',
    laufzeit: '12 Monate',
    rating: 4,
    highlights: ['Fahrraddiebstahl', 'Keine Selbstbeteiligung'],
  },
  {
    id: 'gothaer-hausrat',
    kategorie: 'hausrat',
    name: 'Gothaer',
    preisProMonat: '4,40',
    laufzeit: '24 Monate',
    rating: 4,
    highlights: ['Naturgefahren', 'Grob-Fahrlässigkeit'],
    partnerangebot: true,
  },
  {
    id: 'cosmosdirekt-hausrat',
    kategorie: 'hausrat',
    name: 'CosmosDirekt',
    preisProMonat: '3,99',
    laufzeit: '12 Monate',
    rating: 3,
    highlights: ['Online-Abschluss', 'Bonus: 1 Monat gratis'],
  },
];

export function getAnbieterByKategorie(k: VertragKategorie): Anbieter[] {
  return ANBIETER.filter((a) => a.kategorie === k);
}

export const KATEGORIE_META: Record<VertragKategorie, { headerTitle: string; sublineCount: string }> = {
  strom:       { headerTitle: 'Stromanbieter vergleichen',     sublineCount: '~40 Anbieter' },
  internet:    { headerTitle: 'Internetanbieter vergleichen',  sublineCount: '~25 Anbieter' },
  telefon:     { headerTitle: 'Mobilfunkanbieter vergleichen', sublineCount: '~30 Anbieter' },
  haftpflicht: { headerTitle: 'Versicherungen vergleichen',    sublineCount: '~20 Anbieter' },
  hausrat:     { headerTitle: 'Versicherungen vergleichen',    sublineCount: '~20 Anbieter' },
};
